builds:
  - binary: teler
    main: cmd/teler/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ldflags:
      - -s -w -X ktbs.dev/teler/common.Version={{.Version}}
  
archives:
  - id: tgz
    format: tar.gz
    replacements:
        darwin: macOS
    format_overrides:
        - goos: windows
          format: zip
