threat:
  - cat: "Common Web Attack"
    url: "https://github.com/enygma/expose/raw/master/src/Expose/filter_rules.json"

filter:
  - cat: "Bad IP Address"
    url: "https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/raw/master/_generator_lists/bad-ip-addresses.list"

  - cat: "Bad Referrer"
    url: "https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/raw/master/_generator_lists/bad-referrers.list"

  - cat: "Bad Crawler"
    url: "https://github.com/JayBizzle/Crawler-Detect/raw/master/raw/Crawlers.txt"

  - cat: "Directory Bruteforce"
    url: "https://github.com/maurosoria/dirsearch/raw/master/db/dicc.txt"