threat:
  - cat: "Common Web Attack"
    url: "https://raw.githubusercontent.com/enygma/expose/master/src/Expose/filter_rules.json"

filter:
  - cat: "Bad IP Address"
    url: "https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-ip-addresses.list"

  - cat: "Bad Referrer"
    url: "https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-referrers.list"

  - cat: "Bad Crawler"
    url: "https://raw.githubusercontent.com/JayBizzle/Crawler-Detect/master/raw/Crawlers.txt"

  - cat: "Directory Bruteforce"
    url: "https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt"