name: Build
on:
  push:
    paths-ignore:
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - CONTRIBUTION_LICENSE_AGREEMENT.md
      - README.md
      - .gitignore
    branches:
      - master
      - development
  pull_request:
  
jobs:          
  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@master

      - name: Test
        run: go test .
        working-directory: cmd/teler/

      - name: Build
        run: go build .
        working-directory: cmd/teler/
