name: Publish to Docker Hub on creation of a new release
on: 
  release:
    types: [published]

jobs:
  build:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tags: latest
