name: Linter
on:
  push:
    paths-ignore:
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - CONTRIBUTION_LICENSE_AGREEMENT.md
      - README.md
      - .gitignore
    tags:
      - v*
    branches:
      - master
      - development
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29
          args: -e SA9003