name: Review
on:
  push:
    branches:
      - development

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: SonarQube Scanner
      uses: kitabisa/sonarqube-action@development
      with:
        host: ${{ secrets.SONARQUBE_HOST_TEST }}
        login: ${{ secrets.SONARQUBE_TOKEN_TEST }}
        projectKey: "teler"
        projectName: "teler"